name: ngx_hidden_signature_patch
on: ["push", "pull_request"]
jobs:
  build_and_test:
    strategy:
      matrix:
       ngx: ['1.23.1', '1.22.0', '1.20.2', '1.18.0', '1.16.1', '1.14.2']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # Run build of the application
    - name: Run build - nginx ${{ matrix.ngx }}
      run: |
        ls -al
